### ISSUE TITLE
addDependency is not properly splitting the fileContents using the OS specific marker

### ISSUE THREAD

**Issue by SaigeArk** [dustinspecker/ng-add-dep#1]
When a new module is generated in ng-poly:module it looks like ng-add-dep is using the OS EOL marker, however the file is generated with a different line ending.  I have not tracked down why or where this is happening yet. The resulting module looks like this:

```
 'ui.router'
 (function () {
    'use strict';
    /* @ngdoc object
    * @name admin
    * @description
    *
    */
    angular
        .module('admin', [
        ]);
}());
```

The proximate solution I found was to modify line 14 from:

```
var lines = fileContents.split(endOfLine)
```

to

```
var lines = fileContents.split(/[\r\n]+/g)
```

**Comment by dustinspecker** [comment]
Ah, great catch. Some folks ran into this a few months ago and we had no idea why, but this explains that perfectly. I'm on vacation the next few days, but I'll try to fix this module and ng-poly as soon as possible.

**Comment by dustinspecker** [comment]
95c80b8d90567d4287ba7ceb43dafea0f500668c Fixed in this module. I'll update the dep in ng-poly and the route utils soon.

**Comment by dustinspecker** [comment]
Thanks again for catching this!
